import { StyleSheet, Dimensions } from "react-native"
import { RFPercentage, RFValue } from "react-native-responsive-fontsize"

let { width, height } = Dimensions.get("window");
let numberGrid = 2;
let widthGrid = (width - 45) / numberGrid;
let itemHeight = height / 3 - 100;
let middleHight = height / 2 - 100;
let height60 = height * 0.6

const iconMsgSize = height < 600 ? 25 : 30
const wrapIconMsg = height < 600 ? 40 : 50


const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentSafe: {
        flex: 1
    },
    blocoHeader: {
        height: 0.2 * height,
        width: '100%',
        paddingLeft: '3%',
        paddingRight: '3%',
        paddingTop: 0.03 * height,
    },
    blocoLinear: {
        flex: 1,
        position: 'absolute',
        width: '100%',
    },
    lineCheckbox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#CCC',
        borderRadius: 10,
        padding: 5,
    },
    checkbox: {
        margin: 8,
    },
    wrapperTouchIcone: {
        width: '18%',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    wrapperTouchTexto: {
        width: '82%',
    },
    infoView: {
        flex: 1,
        fontSize: 20,
        backgroundColor: 'transparent'
    },
    wrapperBtn: {
        height: 0.115 * height,
    },
    wrapperLogo: {
        flex: 1,
        backgroundColor: '#FFF',
        width: '100%',
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.43,
        shadowRadius: 9.51,
        elevation: 15,
        zIndex: 1,
    },
    blocoSituacao: {
        height: 0.15 * height,
        minHeight: 0.15 * height,
        flex: 1,
        justifyContent: 'space-evenly',
        alignItems: 'center',
        width: '100%',
        zIndex: 2,
    },
    blocoBottom: {
        height: 0.6 * height,
        paddingBottom: '3%',
        paddingLeft: '3%',
        paddingRight: '3%',
    },
    blocoFull: {
        flex: 1,
        borderRadius: 30,
        width: '100%',
        backgroundColor: '#FFF',
        padding: '3%',
        justifyContent: 'space-between',
        marginBottom: 10,
        height: 0.55 * height,
        minHeight: 0.58 * height,
    },
    blocoMessages: {
        flex: 1,
        backgroundColor: '#868682',
        height: 0.41 * height,
        maxHeight: 0.41 * height,
        padding: '3%',
        borderRadius: 30,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.43,
        shadowRadius: 9.51,
        elevation: 10,
    },
    blocoInfo: {
        height: 0.5 * height,
        minHeight: 0.5 * height,
        maxHeight: 0.5 * height,
        width: '100%',
        padding: '3%',
        paddingTop: 0.03 * height,
        flex: 1,
    },
    blocoAcesso: {
        height: 0.8 * height,
        minHeight: 0.8 * height,
        maxHeight: 0.8 * height,
        width: '100%',
        padding: '3%',
        paddingTop: 0.03 * height,
        flex: 1,
    },
    wrapperAcesso: {
        flex: 1,
        backgroundColor: '#FFF',
        width: '100%',
        borderRadius: 30,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.43,
        shadowRadius: 9.51,
        elevation: 15,
    },
    wrapperInfo: {
        flex: 1,
        justifyContent: 'space-between',
        backgroundColor: '#FFF',
        width: '100%',
        height: 0.45 * height,
        minHeight: 0.45 * height,
        maxHeight: 0.45 * height,
        padding: '5%',
        borderRadius: 40,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.43,
        shadowRadius: 9.51,
        elevation: 15,
    },
    lineTitleMessage: {
        borderBottomColor: '#FFF',
        borderBottomWidth: 1,
        paddingBottom: 8
    },
    lineVersion: {
        flex: 1,
        height: 0.1 * height,
        paddingTop: 5,
        alignItems: 'center'
    },
    blocoTabs: {
        flex: 1,
        backgroundColor: '#FFF',
        height: 0.11 * height,
        maxHeight: 0.11 * height,
        minHeight: 0.11 * height,
        borderRadius: 35,
        borderWidth: 4,
        borderColor: '#CCC',
        justifyContent: 'space-around',
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 7,
        },
        shadowOpacity: 0.43,
        shadowRadius: 9.51,
        elevation: 5,
    },
    wrapperMap: {
        alignSelf: 'center',
        top: 20,
        width: '94%',
        height: 0.75 * height,
        borderRadius: 25,
        overflow: 'hidden',
    },
    mapa: {
        width: '100%',
        height: 0.75 * height,
    },
    wrapperFooter: {
        height: 0.14 * height,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        zIndex: 10,
        borderRadius: 25,
        paddingLeft: '3%',
        paddingRight: '3%',
        backgroundColor: '#FFF',
    },
    blocoFooter: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        top: 0.8 * height,
        height: 0.14 * height,
        position: 'absolute',
        paddingLeft: '3%',
        paddingRight: '3%',
        backgroundColor: 'transparent',
        marginRight: 10,
    },
    wrapperIcon: {
        backgroundColor: 'rgba(255,255,255,0.325)',
        marginRight: 0,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        height: wrapIconMsg,
        width: wrapIconMsg,
        maxHeight: wrapIconMsg,
        maxWidth: wrapIconMsg,
        minWidth: wrapIconMsg,
        borderRadius: wrapIconMsg / 2,
    },
    wrapperIconOpen: {
        marginRight: 0,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
        width: 50,
        maxHeight: 50,
        maxWidth: 50,
        minWidth: 50,
    },
    iconMsg: {
        width: iconMsgSize,//30,
        height: iconMsgSize,//30,
    },
    linhaBtn: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        minHeight: 55,
        alignItems: 'center',
        marginRight: 25,
        marginTop: 8,
        width: '100%',
    },
    linhaIcone: {
        flex: 1,
        width: '20%',
        maxWidth: '20%',
        justifyContent: 'center',
        alignItems: 'center'
    },
    linhaRede: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F00',
        position: 'absolute',
        maxHeight: 100,
        minHeight: 100,
        zIndex: 1000,
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 20,
        paddingRight: 20,
        width: '100%',
    },
    containerLoading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#00CCCC'
    },
    btnMapType: {
        position: 'absolute',
        top: 60,
        zIndex: 10000,
        backgroundColor: 'rgba(255,255,255,0.5)',
        right: 10,
        width: 40,
        height: 40,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnInfo: {
        flex: 1,
        backgroundColor: 'transparent',
        height: 0.115 * height,
        maxHeight: 0.115 * height,
        minHeight: 0.115 * height,
        borderRadius: 35,
        borderWidth: 4,
        justifyContent: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        paddingLeft: 0,
    },
    btnGrant: {
        maxWidth: '90%',
        minWidth: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#28cc00', 
        maxHeight: 45,
        minHeight: 45,
        width: '100%',
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
    },
    btnSave: {
        width: '100%',
        backgroundColor: '#28cc00',
        maxHeight: 45,
        minHeight: 45,
        marginTop: 10,
        marginBottom: 10,
        paddingLeft: 30,
        paddingRight: 30,
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
    },


    /* images */
    logoInicial: {
        width: 300,
        height: 300,
        resizeMode: 'contain',
    },


    /* textos */
    textoSearchModal: {
        marginLeft: 20,
        fontSize: 15,
        lineHeight: 22,
        fontWeight: '700'
    },
    textoData: {
        textAlign: 'center',
        fontFamily: 'avenirBlack'
    },
    textoRede: {
        color: '#FFF',
        textAlign: 'center',
        fontSize: 15,
        fontFamily: 'avenir'
    },
    textoNivel: {
        color: '#FFF',
        fontSize: RFPercentage(3),//20,
        fontFamily: 'avenirRoman',
    },
    texto16Regular: {
        color: '#333',
        fontSize: 16,
        fontWeight: '400',
    },
    textoSituacao: {
        color: '#FFF',
        fontSize: RFPercentage(5), //34,
        textTransform: 'uppercase',
        fontFamily: 'avenirBlack',
    },
    textoTitleMessage: {
        color: '#FFF',
        fontSize: RFPercentage(3.5), //20,
        textAlign: 'center',
        fontFamily: 'avenirBlack',
    },
    texto14WhiteBold: {
        color: '#FFF',
        fontSize: RFPercentage(2.3), //15,
        fontFamily: 'avenirBlack',
    },
    texto14White: {
        color: '#FFF',
        fontSize: RFPercentage(2.3), //16,
        fontFamily: 'avenir',
    },

    modal: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        backgroundColor: 'rgba(0,0,0,0.7)',
    },
    modalPermission: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingTop: height / 2 - 125,
        padding: 10,
        backgroundColor: 'rgba(0,0,0,0.7)',
    },
    wrapperModal: {
        margin: 20,
        backgroundColor: '#FFF',
        borderRadius: 25,
        paddingTop: 0,
        paddingLeft: '5%',
        paddingRight: '5%',
        paddingBottom: '8%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        minHeight: 200,
        maxHeight: '80%',
        width: '90%'
    },
    innerModal: {
        flex: 1,
        backgroundColor: '#FFF',
        height: '10%',
        maxHeight: '80%',
        marginLeft: '5%',
        marginRight: '5%',
        justifyContent: 'space-between',
        borderRadius: 25
    },
    innerModalSearch: {
        flex: 1,
        backgroundColor: '#FFF',
        marginLeft: '5%',
        marginRight: '5%',
        justifyContent: 'space-between',
        height: 100,
        maxHeight: 100,
        minHeight: 100,
        borderRadius: 40
    },
    innerModalPermission: {
        flex: 1,
        backgroundColor: '#FFF',
        marginLeft: '5%',
        marginRight: '5%',
        justifyContent: 'center',
        alignItems: 'center',
        height: 100,
        maxHeight: 100,
        minHeight: 250,
        borderRadius: 40,
        paddingBottom: 30,
    },
    modalHeader: {
        alignSelf: 'flex-end',
        paddingEnd: '3%',
        paddingTop: '5%',
    },
    modalFooter: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 15,
    },
    modalContent: {
        flex: 1,
        justifyContent: 'center',
        marginTop: '2%',
        marginBottom: '5%',
        marginLeft: '5%',
        marginRight: '5%',
    },
    modalContentSearch: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: '2%',
        marginBottom: '2%',
        marginLeft: '5%',
        marginRight: '10%',
        paddingRight: 10,
    },
    btnCloseModal: {
        fontSize: 20,
    },
    textoContentModal: {
        color: '#333',
        fontSize: RFPercentage(2.3),//18,
        lineHeight: RFPercentage(3),
        fontFamily: 'avenirRoman',
        overflow: 'scroll',
        textAlign: 'justify',
    },
})
export default styles